# Generated by Django 4.2.16 on 2024-10-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('comment', models.TextField(max_length=200)),
                ('imageURL', models.URLField()),
                ('yumFactor', models.IntegerField()),
            ],
        ),
    ]
